languageCode = "en"
languageName = "English"
weight = 1
title = "Moein"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "English description"

[author]
  name = "Mohammad-Moein Arabi"
  image = "img/moein.JPG"
  headline = "Computer engineering student"
  bio = "This is bio"
  links = [
    { github = "https://github.com/ilovebacteria" },
    { linkedin = "https://www.linkedin.com/in/moein-arabi/" },
    { telegram = "https://t.me/moein_arabi" },
  ]