languageCode = "fa"
languageName = "Persian"
weight = 2
title = "معین"

[params]
  displayName = "فارسی"
  isoCode = "fa"
  rtl = true
  dateFormat = "2 January 2006"
  description = "زبان فارسی"

[author]
  name = "محمدمعین عربی"
  image = "img/moein.JPG"
  headline = "دانشجوی رشته مهندسی کامپیوتر"
  bio = "بیو من"
  links = [
    { github = "https://github.com/ilovebacteria" },
    { linkedin = "https://www.linkedin.com/in/moein-arabi/" },
    { telegram = "https://t.me/moein_arabi" },
  ]