# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#   name = "Docs"
#   pageRef = "docs"
#   weight = 10

# [[main]]
#   name = "Samples"
#   parent = "Examples"
#   pageRef = "samples"
#   weight = 16

# [[main]]
#   name = "Merch"
#   url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#   weight = 100

[[main]]
  name = "وبلاگ"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "پروژه"
  url = "/projects"
  weight = 20

[[main]]
  name = "درباره من"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ilovebacteria"
  weight = 100


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "تگ ها"
   pageRef = "tags"
   weight = 10

[[footer]]
   name = "دسته بندی"
   pageRef = "categories"
   weight = 30
